# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-04 06:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='Date_Of_Joining',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='Employee_ID',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='Employee_Name',
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
            preserve_default=False,
        ),
    ]
