# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-04 06:54
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20160804_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='City',
            field=models.TextField(default='Chandigarh', max_length=30),
        ),
        migrations.AddField(
            model_name='employee',
            name='Date_Of_Joining',
            field=models.DateField(default=datetime.datetime(2016, 8, 4, 6, 54, 55, 699000, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='Employee_Name',
            field=models.TextField(default='Mona', max_length=254),
        ),
        migrations.AddField(
            model_name='employee',
            name='Province',
            field=models.CharField(default='Chandigarh', max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='user',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
