# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-05 06:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_auto_20160805_1123'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='group',
            new_name='groups',
        ),
    ]
