# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-07 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pharma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pharma_ID', models.TextField(max_length=254)),
                ('Pharma_Name', models.TextField(max_length=254)),
                ('Date_Of_Joining', models.DateField()),
            ],
        ),
    ]
