# -*- coding: utf-8 -*-
# Generated by Django 1.9.5.dev20160312175816 on 2016-03-16 11:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicines',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 16, 11, 18, 3, 617988, tzinfo=utc), verbose_name='expiry Date'),
            preserve_default=False,
        ),
    ]
