# -*- coding: utf-8 -*-
# Generated by Django 1.9.5.dev20160312175816 on 2016-03-16 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_medicines_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicines',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
