# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-17 11:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_medicines_refill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicines',
            name='expiry_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
