# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-07 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=254)),
                ('age', models.TextField(max_length=254)),
                ('sex', models.TextField(max_length=254)),
                ('dob', models.TextField(max_length=254)),
                ('contact', models.TextField(max_length=254)),
                ('patientId', models.TextField(max_length=254)),
            ],
        ),
    ]
