# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-07 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='age',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='contact',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='dob',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='name',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='sex',
            field=models.CharField(max_length=254),
        ),
    ]
