# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-09 20:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_auto_20160307_1425'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='dob',
            new_name='doa',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='age',
            new_name='nod',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='name',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='sex',
        ),
    ]
