# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-10 08:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_auto_20160309_2027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='contact',
            new_name='Contact',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='doa',
            new_name='DateOfBirth',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='nod',
            new_name='NameOfDoctor',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='patientId',
            new_name='PatientId',
        ),
    ]
