# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-25 09:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctor', '0007_auto_20160825_1324'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoneAgeAssessmentPatient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Measurement', models.FloatField()),
                ('Patient_ID', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='doctor.Patient')),
            ],
        ),
    ]
