# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-27 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0008_patienthealthdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='Patient_ID',
            field=models.IntegerField(),
        ),
    ]
