# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-27 07:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0009_auto_20160827_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='FullName',
            field=models.CharField(max_length=30),
        ),
    ]
