# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-27 07:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doctor', '0010_auto_20160827_1303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='Doctor_Visited_Id',
        ),
        migrations.AddField(
            model_name='patient',
            name='DoctorID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
