# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-27 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0012_auto_20160827_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patienthealthdata',
            name='DataOfReading',
            field=models.DateTimeField(blank=True),
        ),
    ]
