# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-10 09:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('practitioner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='practitioner',
            name='Password',
            field=models.TextField(default=datetime.datetime(2016, 3, 10, 9, 40, 17, 910391, tzinfo=utc), max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='practitioner',
            name='User_ID',
            field=models.TextField(default=datetime.datetime(2016, 3, 10, 9, 40, 29, 34729, tzinfo=utc), max_length=254),
            preserve_default=False,
        ),
    ]
